#############################################################################
# Makefile for building: Fonta
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  Fonta.pro
# Template: subdirs
# Command: C:\Qt\5.7\msvc2015\bin\qmake.exe -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile Fonta.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = C:\Qt\5.7\msvc2015\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-src-fonta \
		sub-src-fontadb \
		sub-src-tools-fonts_cleaner \
		sub-src-tools-fonta_classifier \
		sub-src-tools-cogwheel_gen


sub-src-fonta-qmake_all:  FORCE
	@if not exist src\fonta\ mkdir src\fonta\ & if not exist src\fonta\ exit 1
	cd src\fonta\ && $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\fonta\fonta.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\fonta\ && $(MAKE) -f Makefile qmake_all
sub-src-fonta: FORCE
	@if not exist src\fonta\ mkdir src\fonta\ & if not exist src\fonta\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\fonta\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\fonta\fonta.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile
sub-src-fonta-make_first: FORCE
	@if not exist src\fonta\ mkdir src\fonta\ & if not exist src\fonta\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\fonta\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\fonta\fonta.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-src-fonta-all: FORCE
	@if not exist src\fonta\ mkdir src\fonta\ & if not exist src\fonta\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\fonta\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\fonta\fonta.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-src-fonta-clean: FORCE
	@if not exist src\fonta\ mkdir src\fonta\ & if not exist src\fonta\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\fonta\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\fonta\fonta.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-fonta-distclean: FORCE
	@if not exist src\fonta\ mkdir src\fonta\ & if not exist src\fonta\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\fonta\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\fonta\fonta.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-fonta-install_subtargets: FORCE
	@if not exist src\fonta\ mkdir src\fonta\ & if not exist src\fonta\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\fonta\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\fonta\fonta.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-src-fonta-uninstall_subtargets: FORCE
	@if not exist src\fonta\ mkdir src\fonta\ & if not exist src\fonta\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\fonta\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\fonta\fonta.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-src-fontadb-qmake_all:  FORCE
	@if not exist src\fontadb\ mkdir src\fontadb\ & if not exist src\fontadb\ exit 1
	cd src\fontadb\ && $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\fontadb\fontadb.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\fontadb\ && $(MAKE) -f Makefile qmake_all
sub-src-fontadb: FORCE
	@if not exist src\fontadb\ mkdir src\fontadb\ & if not exist src\fontadb\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\fontadb\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\fontadb\fontadb.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile
sub-src-fontadb-make_first: FORCE
	@if not exist src\fontadb\ mkdir src\fontadb\ & if not exist src\fontadb\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\fontadb\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\fontadb\fontadb.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-src-fontadb-all: FORCE
	@if not exist src\fontadb\ mkdir src\fontadb\ & if not exist src\fontadb\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\fontadb\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\fontadb\fontadb.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-src-fontadb-clean: FORCE
	@if not exist src\fontadb\ mkdir src\fontadb\ & if not exist src\fontadb\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\fontadb\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\fontadb\fontadb.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-fontadb-distclean: FORCE
	@if not exist src\fontadb\ mkdir src\fontadb\ & if not exist src\fontadb\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\fontadb\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\fontadb\fontadb.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-fontadb-install_subtargets: FORCE
	@if not exist src\fontadb\ mkdir src\fontadb\ & if not exist src\fontadb\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\fontadb\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\fontadb\fontadb.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-src-fontadb-uninstall_subtargets: FORCE
	@if not exist src\fontadb\ mkdir src\fontadb\ & if not exist src\fontadb\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\fontadb\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\fontadb\fontadb.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-src-tools-fonts_cleaner-qmake_all:  FORCE
	@if not exist src\tools\fonts_cleaner\ mkdir src\tools\fonts_cleaner\ & if not exist src\tools\fonts_cleaner\ exit 1
	cd src\tools\fonts_cleaner\ && $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\tools\fonts_cleaner\fonts_cleaner.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tools\fonts_cleaner\ && $(MAKE) -f Makefile qmake_all
sub-src-tools-fonts_cleaner: FORCE
	@if not exist src\tools\fonts_cleaner\ mkdir src\tools\fonts_cleaner\ & if not exist src\tools\fonts_cleaner\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tools\fonts_cleaner\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\tools\fonts_cleaner\fonts_cleaner.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile
sub-src-tools-fonts_cleaner-make_first: FORCE
	@if not exist src\tools\fonts_cleaner\ mkdir src\tools\fonts_cleaner\ & if not exist src\tools\fonts_cleaner\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tools\fonts_cleaner\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\tools\fonts_cleaner\fonts_cleaner.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-src-tools-fonts_cleaner-all: FORCE
	@if not exist src\tools\fonts_cleaner\ mkdir src\tools\fonts_cleaner\ & if not exist src\tools\fonts_cleaner\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tools\fonts_cleaner\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\tools\fonts_cleaner\fonts_cleaner.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-src-tools-fonts_cleaner-clean: FORCE
	@if not exist src\tools\fonts_cleaner\ mkdir src\tools\fonts_cleaner\ & if not exist src\tools\fonts_cleaner\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tools\fonts_cleaner\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\tools\fonts_cleaner\fonts_cleaner.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-tools-fonts_cleaner-distclean: FORCE
	@if not exist src\tools\fonts_cleaner\ mkdir src\tools\fonts_cleaner\ & if not exist src\tools\fonts_cleaner\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tools\fonts_cleaner\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\tools\fonts_cleaner\fonts_cleaner.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-tools-fonts_cleaner-install_subtargets: FORCE
	@if not exist src\tools\fonts_cleaner\ mkdir src\tools\fonts_cleaner\ & if not exist src\tools\fonts_cleaner\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tools\fonts_cleaner\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\tools\fonts_cleaner\fonts_cleaner.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-src-tools-fonts_cleaner-uninstall_subtargets: FORCE
	@if not exist src\tools\fonts_cleaner\ mkdir src\tools\fonts_cleaner\ & if not exist src\tools\fonts_cleaner\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tools\fonts_cleaner\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\tools\fonts_cleaner\fonts_cleaner.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-src-tools-fonta_classifier-qmake_all:  FORCE
	@if not exist src\tools\fonta_classifier\ mkdir src\tools\fonta_classifier\ & if not exist src\tools\fonta_classifier\ exit 1
	cd src\tools\fonta_classifier\ && $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\tools\fonta_classifier\fonta_classifier.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tools\fonta_classifier\ && $(MAKE) -f Makefile qmake_all
sub-src-tools-fonta_classifier: FORCE
	@if not exist src\tools\fonta_classifier\ mkdir src\tools\fonta_classifier\ & if not exist src\tools\fonta_classifier\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tools\fonta_classifier\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\tools\fonta_classifier\fonta_classifier.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile
sub-src-tools-fonta_classifier-make_first: FORCE
	@if not exist src\tools\fonta_classifier\ mkdir src\tools\fonta_classifier\ & if not exist src\tools\fonta_classifier\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tools\fonta_classifier\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\tools\fonta_classifier\fonta_classifier.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-src-tools-fonta_classifier-all: FORCE
	@if not exist src\tools\fonta_classifier\ mkdir src\tools\fonta_classifier\ & if not exist src\tools\fonta_classifier\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tools\fonta_classifier\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\tools\fonta_classifier\fonta_classifier.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-src-tools-fonta_classifier-clean: FORCE
	@if not exist src\tools\fonta_classifier\ mkdir src\tools\fonta_classifier\ & if not exist src\tools\fonta_classifier\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tools\fonta_classifier\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\tools\fonta_classifier\fonta_classifier.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-tools-fonta_classifier-distclean: FORCE
	@if not exist src\tools\fonta_classifier\ mkdir src\tools\fonta_classifier\ & if not exist src\tools\fonta_classifier\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tools\fonta_classifier\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\tools\fonta_classifier\fonta_classifier.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-tools-fonta_classifier-install_subtargets: FORCE
	@if not exist src\tools\fonta_classifier\ mkdir src\tools\fonta_classifier\ & if not exist src\tools\fonta_classifier\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tools\fonta_classifier\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\tools\fonta_classifier\fonta_classifier.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-src-tools-fonta_classifier-uninstall_subtargets: FORCE
	@if not exist src\tools\fonta_classifier\ mkdir src\tools\fonta_classifier\ & if not exist src\tools\fonta_classifier\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tools\fonta_classifier\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\tools\fonta_classifier\fonta_classifier.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-src-tools-cogwheel_gen-qmake_all:  FORCE
	@if not exist src\tools\cogwheel_gen\ mkdir src\tools\cogwheel_gen\ & if not exist src\tools\cogwheel_gen\ exit 1
	cd src\tools\cogwheel_gen\ && $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\tools\cogwheel_gen\cogwheel_gen.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tools\cogwheel_gen\ && $(MAKE) -f Makefile qmake_all
sub-src-tools-cogwheel_gen: FORCE
	@if not exist src\tools\cogwheel_gen\ mkdir src\tools\cogwheel_gen\ & if not exist src\tools\cogwheel_gen\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tools\cogwheel_gen\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\tools\cogwheel_gen\cogwheel_gen.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile
sub-src-tools-cogwheel_gen-make_first: FORCE
	@if not exist src\tools\cogwheel_gen\ mkdir src\tools\cogwheel_gen\ & if not exist src\tools\cogwheel_gen\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tools\cogwheel_gen\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\tools\cogwheel_gen\cogwheel_gen.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-src-tools-cogwheel_gen-all: FORCE
	@if not exist src\tools\cogwheel_gen\ mkdir src\tools\cogwheel_gen\ & if not exist src\tools\cogwheel_gen\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tools\cogwheel_gen\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\tools\cogwheel_gen\cogwheel_gen.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-src-tools-cogwheel_gen-clean: FORCE
	@if not exist src\tools\cogwheel_gen\ mkdir src\tools\cogwheel_gen\ & if not exist src\tools\cogwheel_gen\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tools\cogwheel_gen\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\tools\cogwheel_gen\cogwheel_gen.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-tools-cogwheel_gen-distclean: FORCE
	@if not exist src\tools\cogwheel_gen\ mkdir src\tools\cogwheel_gen\ & if not exist src\tools\cogwheel_gen\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tools\cogwheel_gen\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\tools\cogwheel_gen\cogwheel_gen.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-tools-cogwheel_gen-install_subtargets: FORCE
	@if not exist src\tools\cogwheel_gen\ mkdir src\tools\cogwheel_gen\ & if not exist src\tools\cogwheel_gen\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tools\cogwheel_gen\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\tools\cogwheel_gen\cogwheel_gen.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-src-tools-cogwheel_gen-uninstall_subtargets: FORCE
	@if not exist src\tools\cogwheel_gen\ mkdir src\tools\cogwheel_gen\ & if not exist src\tools\cogwheel_gen\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tools\cogwheel_gen\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\tools\cogwheel_gen\cogwheel_gen.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: Fonta.pro C:\Qt\5.7\msvc2015\mkspecs\win32-msvc2015\qmake.conf C:\Qt\5.7\msvc2015\mkspecs\features\spec_pre.prf \
		C:\Qt\5.7\msvc2015\mkspecs\common\angle.conf \
		C:\Qt\5.7\msvc2015\mkspecs\common\msvc-base.conf \
		C:\Qt\5.7\msvc2015\mkspecs\common\msvc-desktop.conf \
		C:\Qt\5.7\msvc2015\mkspecs\qconfig.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dcore.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dcore_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dextras.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dextras_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dinput.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dinput_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dlogic.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dlogic_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dquick.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dquick_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickextras.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickinput.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickrender.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3drender.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3drender_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_axbase.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_axbase_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_axcontainer.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_axcontainer_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_axserver.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_axserver_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_bluetooth.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_bluetooth_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_bootstrap_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_charts.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_charts_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_clucene_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_concurrent.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_concurrent_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_core.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_core_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_datavisualization.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_datavisualization_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_dbus.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_dbus_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_designer.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_designer_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_designercomponents_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_gamepad.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_gamepad_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_gui.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_gui_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_help.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_help_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_location.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_location_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_multimedia.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_multimedia_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_multimediawidgets.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_network.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_network_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_nfc.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_nfc_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_opengl.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_opengl_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_openglextensions.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_openglextensions_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_platformsupport_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_positioning.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_positioning_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_printsupport.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_printsupport_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_purchasing.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_purchasing_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_qml.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_qml_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_qmldebug_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_qmltest.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_qmltest_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_quick.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_quick_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_quickcontrols2.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_quickparticles_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_quickwidgets.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_script.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_script_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_scripttools.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_scripttools_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_scxml.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_scxml_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_sensors.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_sensors_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_serialbus.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_serialbus_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_serialport.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_serialport_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_sql.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_sql_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_svg.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_svg_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_testlib.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_testlib_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_uiplugin.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_uitools.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_uitools_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_webchannel.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_webchannel_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_webengine.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_webengine_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_webenginecore.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_webenginecore_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_webenginewidgets.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_webenginewidgets_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_websockets.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_websockets_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_webview.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_webview_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_widgets.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_widgets_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_winextras.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_winextras_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_xml.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_xml_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_xmlpatterns.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_zlib_private.pri \
		C:\Qt\5.7\msvc2015\mkspecs\features\qt_functions.prf \
		C:\Qt\5.7\msvc2015\mkspecs\features\qt_config.prf \
		C:\Qt\5.7\msvc2015\mkspecs\features\win32\qt_config.prf \
		C:\Qt\5.7\msvc2015\mkspecs\win32-msvc2015\qmake.conf \
		C:\Qt\5.7\msvc2015\mkspecs\features\spec_post.prf \
		C:\Qt\5.7\msvc2015\mkspecs\features\exclusive_builds.prf \
		C:\Qt\5.7\msvc2015\mkspecs\features\default_pre.prf \
		C:\Qt\5.7\msvc2015\mkspecs\features\win32\default_pre.prf \
		C:\Qt\5.7\msvc2015\mkspecs\features\resolve_config.prf \
		C:\Qt\5.7\msvc2015\mkspecs\features\exclusive_builds_post.prf \
		C:\Qt\5.7\msvc2015\mkspecs\features\default_post.prf \
		C:\Qt\5.7\msvc2015\mkspecs\features\qml_debug.prf \
		C:\Qt\5.7\msvc2015\mkspecs\features\win32\rtti.prf \
		C:\Qt\5.7\msvc2015\mkspecs\features\precompile_header.prf \
		C:\Qt\5.7\msvc2015\mkspecs\features\warn_on.prf \
		C:\Qt\5.7\msvc2015\mkspecs\features\file_copies.prf \
		C:\Qt\5.7\msvc2015\mkspecs\features\win32\windows.prf \
		C:\Qt\5.7\msvc2015\mkspecs\features\testcase_targets.prf \
		C:\Qt\5.7\msvc2015\mkspecs\features\exceptions.prf \
		C:\Qt\5.7\msvc2015\mkspecs\features\yacc.prf \
		C:\Qt\5.7\msvc2015\mkspecs\features\lex.prf \
		Fonta.pro
	$(QMAKE) -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile Fonta.pro
C:\Qt\5.7\msvc2015\mkspecs\features\spec_pre.prf:
C:\Qt\5.7\msvc2015\mkspecs\common\angle.conf:
C:\Qt\5.7\msvc2015\mkspecs\common\msvc-base.conf:
C:\Qt\5.7\msvc2015\mkspecs\common\msvc-desktop.conf:
C:\Qt\5.7\msvc2015\mkspecs\qconfig.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dcore.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dcore_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dextras.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dextras_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dinput.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dinput_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dlogic.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dlogic_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dquick.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dquick_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickextras.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickextras_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickinput.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickinput_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickrender.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickrender_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3drender.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3drender_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_axbase.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_axbase_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_axcontainer.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_axcontainer_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_axserver.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_axserver_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_bluetooth.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_bluetooth_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_bootstrap_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_charts.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_charts_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_clucene_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_concurrent.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_concurrent_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_core.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_core_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_datavisualization.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_datavisualization_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_dbus.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_dbus_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_designer.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_designer_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_designercomponents_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_gamepad.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_gamepad_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_gui.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_gui_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_help.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_help_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_location.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_location_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_multimedia.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_multimedia_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_multimediawidgets.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_network.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_network_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_nfc.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_nfc_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_opengl.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_opengl_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_openglextensions.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_openglextensions_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_packetprotocol_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_platformsupport_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_positioning.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_positioning_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_printsupport.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_printsupport_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_purchasing.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_purchasing_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_qml.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_qml_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_qmldebug_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_qmldevtools_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_qmltest.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_qmltest_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_quick.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_quick_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_quickcontrols2.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_quickparticles_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_quickwidgets.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_quickwidgets_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_script.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_script_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_scripttools.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_scripttools_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_scxml.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_scxml_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_sensors.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_sensors_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_serialbus.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_serialbus_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_serialport.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_serialport_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_sql.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_sql_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_svg.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_svg_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_testlib.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_testlib_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_uiplugin.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_uitools.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_uitools_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_webchannel.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_webchannel_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_webengine.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_webengine_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_webenginecore.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_webenginecore_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_webenginewidgets.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_webenginewidgets_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_websockets.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_websockets_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_webview.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_webview_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_widgets.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_widgets_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_winextras.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_winextras_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_xml.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_xml_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_xmlpatterns.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_zlib_private.pri:
C:\Qt\5.7\msvc2015\mkspecs\features\qt_functions.prf:
C:\Qt\5.7\msvc2015\mkspecs\features\qt_config.prf:
C:\Qt\5.7\msvc2015\mkspecs\features\win32\qt_config.prf:
C:\Qt\5.7\msvc2015\mkspecs\win32-msvc2015\qmake.conf:
C:\Qt\5.7\msvc2015\mkspecs\features\spec_post.prf:
C:\Qt\5.7\msvc2015\mkspecs\features\exclusive_builds.prf:
C:\Qt\5.7\msvc2015\mkspecs\features\default_pre.prf:
C:\Qt\5.7\msvc2015\mkspecs\features\win32\default_pre.prf:
C:\Qt\5.7\msvc2015\mkspecs\features\resolve_config.prf:
C:\Qt\5.7\msvc2015\mkspecs\features\exclusive_builds_post.prf:
C:\Qt\5.7\msvc2015\mkspecs\features\default_post.prf:
C:\Qt\5.7\msvc2015\mkspecs\features\qml_debug.prf:
C:\Qt\5.7\msvc2015\mkspecs\features\win32\rtti.prf:
C:\Qt\5.7\msvc2015\mkspecs\features\precompile_header.prf:
C:\Qt\5.7\msvc2015\mkspecs\features\warn_on.prf:
C:\Qt\5.7\msvc2015\mkspecs\features\file_copies.prf:
C:\Qt\5.7\msvc2015\mkspecs\features\win32\windows.prf:
C:\Qt\5.7\msvc2015\mkspecs\features\testcase_targets.prf:
C:\Qt\5.7\msvc2015\mkspecs\features\exceptions.prf:
C:\Qt\5.7\msvc2015\mkspecs\features\yacc.prf:
C:\Qt\5.7\msvc2015\mkspecs\features\lex.prf:
Fonta.pro:
qmake: FORCE
	@$(QMAKE) -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile Fonta.pro

qmake_all: sub-src-fonta-qmake_all sub-src-fontadb-qmake_all sub-src-tools-fonts_cleaner-qmake_all sub-src-tools-fonta_classifier-qmake_all sub-src-tools-cogwheel_gen-qmake_all FORCE

make_first: sub-src-fonta-make_first sub-src-fontadb-make_first sub-src-tools-fonts_cleaner-make_first sub-src-tools-fonta_classifier-make_first sub-src-tools-cogwheel_gen-make_first  FORCE
all: sub-src-fonta-all sub-src-fontadb-all sub-src-tools-fonts_cleaner-all sub-src-tools-fonta_classifier-all sub-src-tools-cogwheel_gen-all  FORCE
clean: sub-src-fonta-clean sub-src-fontadb-clean sub-src-tools-fonts_cleaner-clean sub-src-tools-fonta_classifier-clean sub-src-tools-cogwheel_gen-clean  FORCE
distclean: sub-src-fonta-distclean sub-src-fontadb-distclean sub-src-tools-fonts_cleaner-distclean sub-src-tools-fonta_classifier-distclean sub-src-tools-cogwheel_gen-distclean  FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-src-fonta-install_subtargets sub-src-fontadb-install_subtargets sub-src-tools-fonts_cleaner-install_subtargets sub-src-tools-fonta_classifier-install_subtargets sub-src-tools-cogwheel_gen-install_subtargets FORCE
uninstall_subtargets: sub-src-fonta-uninstall_subtargets sub-src-fontadb-uninstall_subtargets sub-src-tools-fonts_cleaner-uninstall_subtargets sub-src-tools-fonta_classifier-uninstall_subtargets sub-src-tools-cogwheel_gen-uninstall_subtargets FORCE

sub-src-fonta-debug:
	@if not exist src\fonta\ mkdir src\fonta\ & if not exist src\fonta\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\fonta\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\fonta\fonta.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile debug
sub-src-fontadb-debug:
	@if not exist src\fontadb\ mkdir src\fontadb\ & if not exist src\fontadb\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\fontadb\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\fontadb\fontadb.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile debug
sub-src-tools-fonts_cleaner-debug:
	@if not exist src\tools\fonts_cleaner\ mkdir src\tools\fonts_cleaner\ & if not exist src\tools\fonts_cleaner\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tools\fonts_cleaner\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\tools\fonts_cleaner\fonts_cleaner.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile debug
sub-src-tools-fonta_classifier-debug:
	@if not exist src\tools\fonta_classifier\ mkdir src\tools\fonta_classifier\ & if not exist src\tools\fonta_classifier\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tools\fonta_classifier\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\tools\fonta_classifier\fonta_classifier.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile debug
sub-src-tools-cogwheel_gen-debug:
	@if not exist src\tools\cogwheel_gen\ mkdir src\tools\cogwheel_gen\ & if not exist src\tools\cogwheel_gen\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tools\cogwheel_gen\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\tools\cogwheel_gen\cogwheel_gen.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile debug
debug: sub-src-fonta-debug sub-src-fontadb-debug sub-src-tools-fonts_cleaner-debug sub-src-tools-fonta_classifier-debug sub-src-tools-cogwheel_gen-debug

sub-src-fonta-release:
	@if not exist src\fonta\ mkdir src\fonta\ & if not exist src\fonta\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\fonta\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\fonta\fonta.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile release
sub-src-fontadb-release:
	@if not exist src\fontadb\ mkdir src\fontadb\ & if not exist src\fontadb\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\fontadb\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\fontadb\fontadb.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile release
sub-src-tools-fonts_cleaner-release:
	@if not exist src\tools\fonts_cleaner\ mkdir src\tools\fonts_cleaner\ & if not exist src\tools\fonts_cleaner\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tools\fonts_cleaner\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\tools\fonts_cleaner\fonts_cleaner.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile release
sub-src-tools-fonta_classifier-release:
	@if not exist src\tools\fonta_classifier\ mkdir src\tools\fonta_classifier\ & if not exist src\tools\fonta_classifier\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tools\fonta_classifier\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\tools\fonta_classifier\fonta_classifier.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile release
sub-src-tools-cogwheel_gen-release:
	@if not exist src\tools\cogwheel_gen\ mkdir src\tools\cogwheel_gen\ & if not exist src\tools\cogwheel_gen\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tools\cogwheel_gen\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\tools\cogwheel_gen\cogwheel_gen.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile release
release: sub-src-fonta-release sub-src-fontadb-release sub-src-tools-fonts_cleaner-release sub-src-tools-fonta_classifier-release sub-src-tools-cogwheel_gen-release

sub-src-fonta-check:
	@if not exist src\fonta\ mkdir src\fonta\ & if not exist src\fonta\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\fonta\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\fonta\fonta.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile check
sub-src-fontadb-check:
	@if not exist src\fontadb\ mkdir src\fontadb\ & if not exist src\fontadb\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\fontadb\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\fontadb\fontadb.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile check
sub-src-tools-fonts_cleaner-check:
	@if not exist src\tools\fonts_cleaner\ mkdir src\tools\fonts_cleaner\ & if not exist src\tools\fonts_cleaner\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tools\fonts_cleaner\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\tools\fonts_cleaner\fonts_cleaner.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile check
sub-src-tools-fonta_classifier-check:
	@if not exist src\tools\fonta_classifier\ mkdir src\tools\fonta_classifier\ & if not exist src\tools\fonta_classifier\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tools\fonta_classifier\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\tools\fonta_classifier\fonta_classifier.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile check
sub-src-tools-cogwheel_gen-check:
	@if not exist src\tools\cogwheel_gen\ mkdir src\tools\cogwheel_gen\ & if not exist src\tools\cogwheel_gen\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tools\cogwheel_gen\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\tools\cogwheel_gen\cogwheel_gen.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile check
check: sub-src-fonta-check sub-src-fontadb-check sub-src-tools-fonts_cleaner-check sub-src-tools-fonta_classifier-check sub-src-tools-cogwheel_gen-check

sub-src-fonta-benchmark:
	@if not exist src\fonta\ mkdir src\fonta\ & if not exist src\fonta\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\fonta\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\fonta\fonta.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile benchmark
sub-src-fontadb-benchmark:
	@if not exist src\fontadb\ mkdir src\fontadb\ & if not exist src\fontadb\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\fontadb\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\fontadb\fontadb.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile benchmark
sub-src-tools-fonts_cleaner-benchmark:
	@if not exist src\tools\fonts_cleaner\ mkdir src\tools\fonts_cleaner\ & if not exist src\tools\fonts_cleaner\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tools\fonts_cleaner\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\tools\fonts_cleaner\fonts_cleaner.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile benchmark
sub-src-tools-fonta_classifier-benchmark:
	@if not exist src\tools\fonta_classifier\ mkdir src\tools\fonta_classifier\ & if not exist src\tools\fonta_classifier\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tools\fonta_classifier\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\tools\fonta_classifier\fonta_classifier.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile benchmark
sub-src-tools-cogwheel_gen-benchmark:
	@if not exist src\tools\cogwheel_gen\ mkdir src\tools\cogwheel_gen\ & if not exist src\tools\cogwheel_gen\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tools\cogwheel_gen\ && ( if not exist Makefile $(QMAKE) C:\Work\Projects\askepit\Fonta\Fonta\src\tools\cogwheel_gen\cogwheel_gen.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile benchmark
benchmark: sub-src-fonta-benchmark sub-src-fontadb-benchmark sub-src-tools-fonts_cleaner-benchmark sub-src-tools-fonta_classifier-benchmark sub-src-tools-cogwheel_gen-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

